### ISSUE TITLE
Callbacks not getting triggered

### ISSUE THREAD

**Issue by tommikas** [ARMmbed/ble-x-nucleo-idb0xa1#13]
Using [this simple application](https://github.com/tommikas/ble-example) on Nucleo F401RE with the X-NUCLEO-IDB05A1 BLE shield.

The device is visible and when I attempt to connect to it none of the callbacks trigger, but the connection  succeeds. However, since the disconnect callback also doesn't trigger, the device doesn't start advertising again after disconnection.

Is mbed OS 5 not supported yet? Should the callbacks even work? Or am I just missing something to get them to trigger?

(The same application compiled for a nrf51-dk target (without this driver obviously) works as expected.)

**Comment by apalmieriGH** [comment]
Did you update your X-NUCLEO-IDB0XA1 as described [here](https://developer.mbed.org/teams/ST/code/BlueNRG-MS-Stack-Updater/)?

**Comment by tommikas** [comment]
Not yet. I'll give it a shot.

**Comment by tommikas** [comment]
Alright, compiled and ran the fw upgrade program. FW changed from 7.1 to 7.2, as reported by ble.getVersion().

The problem still remains. Any other ideas?

**Comment by pan-** [comment]
@tommikas I've found the issue. 
The stack signal that their is events to process only once waiting for the processing to happens.
Therefore, `BLE::init` will signal events before the event handler is registered. 
If you add `ble.onEventsToProcess(eventCallback);` right before `ble.init` everything will work flawlessly.

**Comment by tommikas** [comment]
Thanks! That does indeed fix it.

Should this perhaps be changed to work the same way as e.g. the NRF51822 and NRF51-DK targets do? As mentioned before the same application worked on the NRF51-DK, so that implementation doesn't seem to be as picky about the order of the calls.

Or failing that, it should be documented that the callback needs to be registered before initialization. It makes sense in retrospect, but didn't cross my mind before.

Anyway, closing this.

**Comment by pan-** [comment]
@tommikas @apalmieriGH The description of the behavior from an implementation and user POV should be improved. I think it is also possible to add few things in BLE API to avoid this kind of trap.

**Comment by apalmieriGH** [comment]
@pan- @tommikas Maybe I'm missing something, but it doesn't work on my side. After disconnecting, I can't reconnect again, no event is triggered any more...

**Comment by tommikas** [comment]
@pan- @apalmieriGH 

Yep, seems I may have celebrated prematurely.

I tried disconnect and connecting again a couple of times.
First disconnect triggers the disconnect event correctly, restarting advertising.
However, after that no more events are triggered.

(updated the example code to register callback before init)

**Comment by apalmieriGH** [comment]
Maybe the issue is caused by a deadlock generated by setting `event_triggered = 0;` after calling `ble.processEvents();` try to comment the `if` statement and simply call `ble.processEvents();` in the loop.
Anyway, why don't use the correct approach (with EventQueue) described by the official examples [mbed-os-example-ble](https://github.com/ARMmbed/mbed-os-example-ble)?

**Comment by pan-** [comment]
@tommikas There is a logic error in your application. 
`event_triggered` should be reset prior to the processing of events, not after!
Just swap these two lines: https://github.com/tommikas/ble-example/blob/master/main.cpp#L88-L89

**Comment by tommikas** [comment]
@pan- Yep, that's the issue there. Of course it's safer to do it in that order anyway, but...
According to the API documentation processEvents() should consume all events when called. Is it that calling it may generate further events that it doesn't actually process before returning? At least in this case, I don't think I was triggering any external events in the small window between processEvents() finishing processing and the flag being reset.

Oh and once again, it's slightly confusing that the original code seemed to work with the NRF51-DK without either of these fixes (although I suspect it may possibly have handled one of the events triggered by disconnecting at the start of handling the next connection event, due to where the flag was reset). I wouldn't necessarily expect the two to work exactly identically in every situation, but it seems that there are some implicit expectations that the API documentation doesn't quite manage to express.

@apalmieriGH This code isn't really representative of the actual code I'm working on. It's just a significantly simplified quick hack to 1) get it to fit in smaller devices and 2) to get a better understanding of the issue. I'm not yet sure exactly how I'm going to do the signaling in the actual target application. The EventQueue approach is one option I'm considering.

Anyway, this should be resolved for now, so closing the issue again. Thank you both for your help :)

**Comment by pan-** [comment]
@tommikas 

> Is it that calling it may generate further events that it doesn't actually process before returning?

The ST shield, unlike the Nordic board works with `HCI`. Basically the main board sends commands over UART and the shield will produce an event at a latter point to answer the command. It is something completely asynchronous. In that case, it very likely that an event will be generated right after the whole queue has been processed. 

> At least in this case, I don't think I was triggering any external events in the small window between processEvents() finishing processing and the flag being reset.

The events signaled are not only the one for the end user but also the ones used by the stack. It is difficult to tell just by looking at the code that you will produce events or not and it is highly dependent on the architecture used (Host Client vs everything on a single chip).

> but it seems that there are some implicit expectations that the API documentation doesn't quite manage to express

Got it 100%, it will be improved.

> The EventQueue approach is one option I'm considering.

[mbed-events](https://github.com/ARMmbed/mbed-events) is a good library to do the job, I've use it in all examples and it work as expected.

**Comment by tommikas** [comment]
Got it. Thanks for the clarification.
