### ISSUE TITLE
Request: build process to integrate with mbed-os CLI (v5)

### ISSUE THREAD

**Issue by petertorelli** [ARMmbed/ble-x-nucleo-idb0xa1#17]
Hi,
Can someone add a readme that shows how to use this repo with the mbed CLI? Perhaps using the [mbed beacon](https://developer.mbed.org/teams/Bluetooth-Low-Energy/code/BLE_AltBeacon/) as a start, since it is very simple? I'm not quite sure how to make a lib out of this with mbed, nor how to modify the app or profile JSON to ensure it is included in the link.
Thanks,
Peter

**Comment by apalmieriGH** [comment]
Hi Peter,

you can refer to section [Using ST Nucleo shield on other targets](https://github.com/ARMmbed/mbed-os-example-ble#using-st-nucleo-shield-on-other-targets) in the mbed-os-example-ble page.

Regards
Andrea
