### ISSUE TITLE
setPreferredConnectionParams has not effect

### ISSUE THREAD

**Issue by pmancele** [ARMmbed/ble-x-nucleo-idb0xa1#30]
Hello,

I'm using BLE with this shield and i would like that my device suggest different `conn_min_interval` and `conn_max_interval` than those used by default.

I know that those parameters are chosen by the central device in the end, but the peripheral device can suggest his own connection parameters.

To do this i tried to modify the defines in `BlueNRGGap.h` file:
```c
#define MIN_INT_CONN   0x0006 //=>7.5msec
#define MAX_INT_CONN   0x0C80 //=>4000msec
#define DEF_INT_CONN   0x0140 //=>400msec (default value for connection interval)
```

But this had no effect (it seems to be overwritten anyway)

I also tried to use the function `BlueNRGGap::setPreferredConnectionParams(const ConnectionParams_t *params)` like this:
```c
    gap_params.connectionSupervisionTimeout = 3200;
    gap_params.minConnectionInterval = 6;
    gap_params.maxConnectionInterval = 16;
    gap_params.slaveLatency = 5;

    ble.gap().setPreferredConnectionParams(&gap_params);
```
But it has no effect.. The connection interval is always the conn_max_interval defined on my Linux computer.
I checked the implementation of the function `setPreferredConnectionParams` and it seems that the preffered connection params are written in the `g_preferred_connection_parameters_char_handle` of the gap service. But in the function `btleinit` it is written:
```c
    // update the peripheral preferred conenction parameters handle
    // This value is hardcoded at the moment.
    g_preferred_connection_parameters_char_handle = 10;
```
what does it mean ? Is it possible to indicate the preferred connection params with the ST shield or it isn't implemented yet ?

Regards,
Pierre-Marie

**Comment by apalmieriGH** [comment]
Hi Pierre-Marie,

the setPreferredConnectionParams() BLE API is implemented and is working as expected.
The Peripheral Preferred Connection Parameters is in fact a characteristic of the Gap Service and can be accessed (read/written) through characteristic handle 10 (currently hardcoded).
How do you check the call has no effect? What do you mean with 

> conn_max_interval defined on my Linux computer ?

Kind regards
Andrea

**Comment by pmancele** [comment]
@apalmieriGH Ok, it is indeed creating a characteristic of the Gap Service. But according to what I've read and the schema bellow, I thought that during the connection procedure the peripheral could suggest his preferred connection parameters to the central (my Linux computer here):
![connection_parameters](https://user-images.githubusercontent.com/25764849/28321752-5359e2ec-6bd4-11e7-946d-f242eeac8357.png)
But from what i saw while sniffing the connection with whireshark, the central is actually sending is connection parameters but the device doesn't suggest anything (Even if i use the `setPreferredConnectionParams` function). So when connected the connection interval is always the one imposed by the central. In my case it is always the parameters stored in the Linux bluetooth kernel here `/sys/kernel/debug/bluetooth/hci0/conn_max_interval`

**Howerever**, I can change the connection interval from the device, while connected, by calling the function `BlueNRGGap::updateConnectionParams(Handle_t handle, const ConnectionParams_t *params)`
Like this:
```c
	BLE &ble = BLE::Instance();
	if (ble.getGapState().connected) {
	    gap_params.connectionSupervisionTimeout = 3200;
	    gap_params.minConnectionInterval = 6;
	    gap_params.maxConnectionInterval = 10;
	    gap_params.slaveLatency = 0;

	    if (ble.gap().updateConnectionParams(gap_h, &gap_params) == BLE_ERROR_NONE) {
	    	printf("Update Accepted !\n");
	    }
	}
```
Did i miss something ? I though it was possible to suggest connection parameters from the device during the connection procedure.

**Comment by apalmieriGH** [comment]
@pmancele the suggestion made by the peripheral is included in Gap characteristic set before connection establishment through the `setPreferredConnectionParams()` API. It is up to the central accepting or not such hint by reading the Gap characteristic.
Once connected, the peripheral can request a connection parameters update by sending an L2CAP connection parameter update through the `updateConnectionParams()` API. But again, the central can accept or ignore the request. On success, the event `EVT_BLUE_L2CAP_CONN_UPD_RESP` is triggered. The status returned by `updateConnectionParams()` is just local.

Hope that helps
Andrea

**Comment by pmancele** [comment]
Thank you for this explanations! And yes it helps !

One last question : You indicated that the event `EVT_BLUE_L2CAP_CONN_UPD_RESP` is triggered on success. Indeed i can see this event being triggered after my request, but it is always triggered, even if the request is rejected.
So i looked on the event definition and i found this: 
```c
/**
 * This event is generated when the master responds to the L2CAP connection update request packet.
 * For more info see CONNECTION PARAMETER UPDATE RESPONSE and COMMAND REJECT in Bluetooth Core v4.0 spec.
 */
#define EVT_BLUE_L2CAP_CONN_UPD_RESP		  (0x0800)
typedef __packed struct _evt_l2cap_conn_upd_resp{
  uint16_t conn_handle;         /**< The connection handle related to the event. */
  uint8_t  event_data_length;  /**< Length of following data. */
/**
 * @li 0x13 in case of valid L2CAP Connection Parameter Update Response packet.
 * @li 0x01 in case of Command Reject.
 */
  uint8_t  code;
  uint8_t  identifier;    /**< Identifier of the response. It is equal to the request. */
  uint16_t l2cap_length;  /**< Length of following data. It should always be 2 */
/**
 * Result code (parameters accepted or rejected) in case of Connection Parameter Update
 * Response (code=0x13) or reason code for rejection in case of Command Reject (code=0x01).
 */
  uint16_t result;
} PACKED evt_l2cap_conn_upd_resp;
```
Now i wonder how the get access to the packet `evt_l2cap_conn_upd_resp` when it is received ? Indeed, we could read the field `  uint16_t result` of this packet, to know if the request has been accepted or not !

Thank you,
Pierre-Marie

**EDIT** : the events are handled in the funciton `HCI_Event_CB(void *pckt)` of the file `btle.cpp`.
The event we talked about is handled here : 
```c
        case EVT_BLUE_L2CAP_CONN_UPD_RESP:
          {
            PRINTF("EVT_BLUE_L2CAP_CONN_UPD_RESP\r\n");
          } 
```
I added this to checkk if the update has been accepted:
```c
        case EVT_BLUE_L2CAP_CONN_UPD_RESP:
          {
            evt_l2cap_conn_upd_resp *response = (evt_l2cap_conn_upd_resp*) (blue_evt->data);
            if (response->result == 0) {
            	printf("Update accepted !\n");
            }
            else {
            	printf("Update refused !\n");
            }
          }
```
Is there an other way to get the information that the update has been accepted ? So the main thread could be aware that the update has been accepted/refused

Thank you again

**Comment by apalmieriGH** [comment]
In fact, the event `EVT_BLUE_L2CAP_CONN_UPD_RESP` is triggered on completion of the update connection params procedure started by the peripheral. When started by the central the event generated on procedure completion is `EVT_LE_CONN_UPDATE_COMPLETE`, instead.
In both cases, there is no application callback to be called allowing to access the procedure return status, yet.
I just committed a small change to the library (see commit 1616127fd90a7bbf7dafc939e108a21693da1c41) to parse the events received in both cases.

Hope to be helpful
Andrea

**Comment by pmancele** [comment]
It's clear for me now ! Thank you !
