### ISSUE TITLE
BLE Frequent disconnects and instability with SPBTLE-RF0

### ISSUE THREAD

**Issue by dhwalters423** [ARMmbed/ble-x-nucleo-idb0xa1#35]
Reported by @alphatronicstva - Mbed Cloud customer.
Internal Ref: IOTPAN-60

Background Information
Mbed OS 5.7.5

Description
Custom designed hardware, based on the STM32 F429ZI, with an SPBTLE-RF0 module soldered directly on the board. They have successfully ported this to work with their board.

Using the BLE Heart Rate monitoring application: https://github.com/ARMmbed/mbed-os-example-ble/blob/master/BLE_HeartRate reporting frequent disconnects and instability.

Connects sometimes, very unstable and disconnects after some time automatically.

100% reproducibility from the customer.

**Comment by apalmieriGH** [comment]
@dhwalters423 @alphatronicstva 
please, have a look at this [thread](https://github.com/ARMmbed/mbed-os/issues/3541).

Hope that could help.

**Comment by dhwalters423** [comment]
Caused by the difference between RF0 and RF module. RF module is the one shipped with the IDB05A1 shield and works as expected.
