### ISSUE TITLE
Offset for reading long characteristic

### ISSUE THREAD

**Issue by YoHidden** [ARMmbed/ble-x-nucleo-idb0xa1#36]
Hi there,

I am using the ST shield board X-NUCLEO-IDB05A1 with this library and found that I can not get access to more than 22 bytes when reading a characteristic. My discovered caracteristic is 29 bytes long and after a first successful read access getting 22 bytes, I call a second time the read function but adding an offset of 22 bytes. I am getting an answer of other 22 bytes which are completely wrong and they have nothing to do with the expected remaining 7 bytes.

I have tracked backwards the read function up to the function _ble_error_t BlueNRGGattConnectionClient::read(GattAttribute::Handle_t attributeHandle, uint16_t offset) const_, and found that _offset_ parameter is being ignored, with a simple call to function _aci_gatt_read_charac_val_ which does not use the offset value.

So, how should I proceed to read a full length characteristic with more than 22 bytes ?

Thanks.

**Comment by apalmieriGH** [comment]
Hi YoHidden,
this library is no longer maintened. Please, refer to [cordio-ble-x-nucleo-idb0xa1](https://github.com/ARMmbed/cordio-ble-x-nucleo-idb0xa1)

Regards

**Comment by YoHidden** [comment]
Oops !! ...good to know !!

Thanks.
